name: npspawner
main: cljminecraft.ClojurePlugin
version: 1.0.0
website: http://github.com/ddeaguiar/npspawner
author: ddeaguiar
description: Quick Nether Portal skeleton creator
depend: [cljminecraft]
#unneeded: class-loader-of: cljminecraft
commands:
  npspawner.nether-portal:
    description: Creates the skeleton of a Nether Portal
    permission: npspawner.nether-portal
    usage: /<command>
permissions:
  npspawner.dosomething:
    description: Does something, I'm sure
    default: op
